services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Example123
      - POSTGRES_DATABASE=kadenceChallenge
    ports:
      - "5000:8800"
    depends_on:
      - postgres
    networks:
      - mynet
  postgres:
    image: "postgres:latest"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Example123
      POSTGRES_DB: kadenceChallenge
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
